### ISSUE TITLE
AutoLayout

### ISSUE THREAD

**Issue by binyamg** [iwasrobbed/RPFloatingPlaceholders#18]
Does this/textView support autolayout? 
- I see that it says so on the Readme. But why does it have to be initialized with a frame or storyboard. I would like to create it programmatically and use autolayout to position it. Is that possible?

**Comment by PavelGerashchenko** [comment]
+

**Comment by iwasrobbed** [comment]
Thanks @ben95beng & @PavelGerashchenko, I'll work on fixing this soon

**Comment by chrise86** [comment]
Also in need of this :)

**Comment by iwasrobbed** [comment]
Welcoming any and all pull requests to fix this. I'll be pretty busy with other work for the next few months at the very least so unfortunately I won't have time to look into it.

**Comment by nickolas-pohilets** [comment]
It should be easy to support autolayout with current design if RPFloatingPlaceholderAnimateDownward is removed. Otherwise, it should be a UIView that aggregates UILabel and UITextField/UITextView, rather then subclassing them.

**Comment by GopalPatel1989** [comment]
It does not support autolayout, i want it badly. Look at my screenshot
![screen shot 2016-07-08 at 12 43 52 pm](https://cloud.githubusercontent.com/assets/9877820/16680046/c53548f4-4509-11e6-820f-90ec82a7d681.png)

**Comment by iwasrobbed** [comment]
Use https://github.com/jverdi/JVFloatLabeledTextField instead
