### ISSUE TITLE
Text alignment is not respected by placeholder/floating label.

### ISSUE THREAD

**Issue by deville** [iwasrobbed/RPFloatingPlaceholders#23]
Floating label and placeholder in `RPFloatingPlaceholderTextField` or `RPFloatingPlaceholderTextView` are aligned to the left regardless of alignment of the text.

Alignment of the floating label can be fixed programmatically, but since placeholder is drawn manually there is no way to change its alignment

**Comment by iwasrobbed** [comment]
Closed with #24
