### ISSUE TITLE
FloatingPlaceholder do now moves with textField during animation

### ISSUE THREAD

**Issue by AntonReality** [iwasrobbed/RPFloatingPlaceholders#25]
Hey! I'm using textField.transform = CGAffineTransformMakeTranslation(0, -80), but placeholder stays at the start point of the textField. How can i fix this, or recalculate the new position of the label?
textField.floatingLabel.transform = CGAffineTransformMakeTranslation(0, -80) only makes what expected if floatingplaceholder already shown.

**Comment by iwasrobbed** [comment]
Use https://github.com/jverdi/JVFloatLabeledTextField instead
